/* Login Actions */
export const FETCH_ALL_DESIGN = 'FETCH_ALL_DESIGN';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
export const SEARCH_DESIGNS = 'SEARCH_DESIGNS';
export const FETCH_CHILD_VERSIONS = 'FETCH_CHILD_VERSIONS';

